// src/entities/tour/model/tours.mock.ts

export type Difficulty = "easy" | "medium" | "hard";
export type Season = "spring" | "summer" | "autumn" | "winter";
export type TourCategory = "nature" | "culture" | "adventure" | "spiritual";

export type Tour = {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: TourCategory[];
  difficulty: Difficulty;
  durationDays: number;
  priceFrom: number;
  seasons: Season[];
  coverImage: string;
  rating: number;
  reviewsCount: number;
  isBestseller: boolean;
  isNew: boolean;
  departureCity: string;
  highlights: string[];
  groupSizeMax: number;
};

export const MOCK_TOURS: Tour[] = [
  {
    id: "1",
    slug: "baikal-olkhon",
    title: "Священные берега Байкала",
    description: "Семидневное путешествие по западному берегу Байкала — от Иркутска до острова Ольхон. Шаманские места, бирюзовая вода, нетронутая тайга и закаты на мысе Бурхан.",
    category: ["nature", "spiritual"],
    difficulty: "easy",
    durationDays: 7,
    priceFrom: 58000,
    seasons: ["summer", "spring", "autumn"],
    coverImage: "https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?w=600&q=80",
    rating: 4.9,
    reviewsCount: 87,
    isBestseller: true,
    isNew: false,
    departureCity: "Иркутск",
    highlights: ["Мыс Бурхан", "Остров Ольхон", "Скалы Хобой", "Байкальский омуль"],
    groupSizeMax: 12,
  },
  {
    id: "2",
    slug: "datsan-path",
    title: "Путь дацанов",
    description: "Пятидневное погружение в буддийскую культуру Бурятии. Иволгинский дацан, встреча с ламами, медитации в горах Хамар-Дабана и знакомство с традициями бурятского народа.",
    category: ["spiritual", "culture"],
    difficulty: "easy",
    durationDays: 5,
    priceFrom: 42000,
    seasons: ["spring", "summer", "autumn", "winter"],
    coverImage: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&q=80",
    rating: 4.8,
    reviewsCount: 54,
    isBestseller: false,
    isNew: false,
    departureCity: "Улан-Удэ",
    highlights: ["Иволгинский дацан", "Нетленный Итигэлов", "Медитация", "Горловое пение"],
    groupSizeMax: 10,
  },
  {
    id: "3",
    slug: "barguzin-wild",
    title: "Дикая долина Баргузина",
    description: "Восьмидневный трекинг по Баргузинской долине — одному из самых труднодоступных мест России. Горячие источники Умхей, эвенкийские стойбища и дикие звери.",
    category: ["adventure", "nature"],
    difficulty: "hard",
    durationDays: 8,
    priceFrom: 89000,
    seasons: ["summer", "autumn"],
    coverImage: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80",
    rating: 4.95,
    reviewsCount: 31,
    isBestseller: false,
    isNew: true,
    departureCity: "Улан-Удэ",
    highlights: ["Источники Умхей", "Эвенки", "Чум", "Святой Нос"],
    groupSizeMax: 8,
  },
  {
    id: "4",
    slug: "jimny-adventure",
    title: "Джип-приключения на Jimny",
    description: "Три дня внедорожного безумия по горам и бродам Бурятии. Хамар-Дабан, южный Байкал, термальные источники Аршана — туда, куда не доедет ни один автобус.",
    category: ["adventure"],
    difficulty: "medium",
    durationDays: 3,
    priceFrom: 35000,
    seasons: ["summer", "autumn"],
    coverImage: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",
    rating: 4.85,
    reviewsCount: 42,
    isBestseller: true,
    isNew: false,
    departureCity: "Улан-Удэ",
    highlights: ["Броды", "Перевалы", "Аршан", "Хамар-Дабан"],
    groupSizeMax: 6,
  },
  {
    id: "5",
    slug: "ulan-ude-culture",
    title: "Улан-Удэ — город двух культур",
    description: "Двухдневный городской тур по столице Бурятии. Голова Ленина, буузные, этнографический музей, буддийские храмы и современная жизнь на стыке Азии и России.",
    category: ["culture"],
    difficulty: "easy",
    durationDays: 2,
    priceFrom: 18000,
    seasons: ["spring", "summer", "autumn", "winter"],
    coverImage: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80",
    rating: 4.7,
    reviewsCount: 63,
    isBestseller: false,
    isNew: false,
    departureCity: "Улан-Удэ",
    highlights: ["Голова Ленина", "Этномузей", "Буузная", "Арт-квартал"],
    groupSizeMax: 15,
  },
  {
    id: "6",
    slug: "sayany-trek",
    title: "Треккинг в Восточных Саянах",
    description: "Шесть дней пешего похода по хребтам Восточных Саян. Альпийские луга, ледниковые озера, перевалы и ночи под звёздным небом Сибири без единого источника света.",
    category: ["adventure", "nature"],
    difficulty: "hard",
    durationDays: 6,
    priceFrom: 67000,
    seasons: ["summer"],
    coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    rating: 4.9,
    reviewsCount: 28,
    isBestseller: false,
    isNew: true,
    departureCity: "Улан-Удэ",
    highlights: ["Ледниковые озера", "Перевалы 2400м", "Альпийские луга", "Дикая природа"],
    groupSizeMax: 8,
  },
  {
    id: "7",
    slug: "baikal-winter",
    title: "Зимний Байкал",
    description: "Четыре дня на льду Байкала в феврале. Прозрачный лёд толщиной два метра, торосы, нерпы и ночевка в юрте прямо на замёрзшем озере. Самый фотогеничный тур.",
    category: ["nature", "adventure"],
    difficulty: "medium",
    durationDays: 4,
    priceFrom: 52000,
    seasons: ["winter"],
    coverImage: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80",
    rating: 4.95,
    reviewsCount: 71,
    isBestseller: true,
    isNew: false,
    departureCity: "Иркутск",
    highlights: ["Лёд Байкала", "Торосы", "Нерпа", "Юрта на льду"],
    groupSizeMax: 10,
  },
  {
    id: "8",
    slug: "arshan-wellness",
    title: "Аршан — источники и горы",
    description: "Три дня в курортном посёлке Аршан у подножия Восточных Саян. Термальные источники, водопады, буддийские ступы и пешие прогулки по горным тропам.",
    category: ["nature", "spiritual"],
    difficulty: "easy",
    durationDays: 3,
    priceFrom: 28000,
    seasons: ["spring", "summer", "autumn"],
    coverImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    rating: 4.75,
    reviewsCount: 49,
    isBestseller: false,
    isNew: false,
    departureCity: "Улан-Удэ",
    highlights: ["Термальные источники", "Водопады", "Ступы", "Горные тропы"],
    groupSizeMax: 12,
  },
  {
    id: "9",
    slug: "chivyrkuy-bay",
    title: "Чивыркуйский залив",
    description: "Пять дней на восточном берегу Байкала в самом тёплом заливе озера. Рыбалка, купание, катание на лодке и полное отсутствие цивилизации вокруг.",
    category: ["nature"],
    difficulty: "easy",
    durationDays: 5,
    priceFrom: 44000,
    seasons: ["summer"],
    coverImage: "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?w=600&q=80",
    rating: 4.8,
    reviewsCount: 38,
    isBestseller: false,
    isNew: true,
    departureCity: "Улан-Удэ",
    highlights: ["Тёплое купание", "Рыбалка", "Лодки", "Дикий берег"],
    groupSizeMax: 10,
  },
  {
    id: "10",
    slug: "buryat-gastro",
    title: "Гастрономическая Бурятия",
    description: "Четыре дня гастрономического путешествия по Бурятии. Буузы, позы, омуль, саган-дали, тарасун — пробуем всё что едят и пьют буряты, готовим сами в семейных домах.",
    category: ["culture"],
    difficulty: "easy",
    durationDays: 4,
    priceFrom: 38000,
    seasons: ["spring", "summer", "autumn", "winter"],
    coverImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
    rating: 4.85,
    reviewsCount: 56,
    isBestseller: false,
    isNew: false,
    departureCity: "Улан-Удэ",
    highlights: ["Буузы", "Омуль", "Мастер-класс", "Семейные дома"],
    groupSizeMax: 8,
  },
];